### ISSUE TITLE
wildcard option?

### ISSUE THREAD

**Issue by n1ete** [vbotka/ansible-certificate#1]
is it possible to add wildcard selfsigned certs? 
best regards and thanks for this well writen playbook

**Comment by vbotka** [comment]
Thank you for your comments.

It should be possible. I have never tested self-signed wildcard certs, though.

* There are restrictions. See
https://superuser.com/questions/1374959/self-signed-wildcard-certificate

* And there is also a guide on how to do it. See
https://gist.github.com/bitoiu/9e19962b991a71165268

**Comment by vbotka** [comment]
Closed. Feel free to ask to reopen.
