### ISSUE TITLE
pyopenssl deprecated?

### ISSUE THREAD

**Issue by n1ete** [vbotka/ansible-certificate#2]
since pyopenssl is soon to be dropped, is this an easy resolvable task?

**Comment by vbotka** [comment]
Yes. In fact, this has already been resolved. The modules openssl_* docs say "The module can use the cryptography Python library or the pyOpenSSL Python library." At the moment vars/default variables "certificate_packages" list both packages. This can be customized. The sanity checks whether any of the packages have been installed. See variables "al_sanity_packages_required" in vars/defaults.

**Comment by vbotka** [comment]
Closed. Feel free to ask to reopen.
